//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPurchaseHistoryItem
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int OrderId { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual User User { get; set; }
    }
}
